### ISSUE TITLE
Add Adafruit_DHT as a pre-requisite in setup.py

### ISSUE THREAD

**Issue by ffund** [keidyalmonte/Plant-Hub#17]
In `setup.py`, add an `install_requires` line so that the `Adafruit_DHT` library will be install automatically when you install your library.

See https://packaging.python.org/guides/distributing-packages-using-setuptools/#install-requires for info.

Currently, if you don't have the DHT library installed, the demo script will fail with:

```
  File "demo.py", line 1, in <module>
    import planthub
  File "/home/pi/sp21/Plant-Hub/planthub.py", line 2, in <module>
    import Adafruit_DHT
ModuleNotFoundError: No module named 'Adafruit_DHT'
```

(which is not a user-friendly error message) - if you add the pre-requisite to the `setup.py`, it will either be installed OR the user will be informed of the problem during installation, which makes more sense.

**Comment by keidyalmonte** [comment]
> In `setup.py`, add an `install_requires` line so that the `Adafruit_DHT` library will be install automatically when you install your library.
> 
> See https://packaging.python.org/guides/distributing-packages-using-setuptools/#install-requires for info.
> 
> Currently, if you don't have the DHT library installed, the demo script will fail with:
> 
> ```
>   File "demo.py", line 1, in <module>
>     import planthub
>   File "/home/pi/sp21/Plant-Hub/planthub.py", line 2, in <module>
>     import Adafruit_DHT
> ModuleNotFoundError: No module named 'Adafruit_DHT'
> ```
> 
> (which is not a user-friendly error message) - if you add the pre-requisite to the `setup.py`, it will either be installed OR the user will be informed of the problem during installation, which makes more sense.

**Added the `Adafruit_DHT` library using the `install_requires` functionality from the setup tools.**
![image](https://user-images.githubusercontent.com/60752427/113912025-ac8aa780-97a8-11eb-8db5-6e1ed815c1d0.png)
