### ISSUE TITLE
Test humidity sensor

### ISSUE THREAD

**Issue by ffund** [keidyalmonte/Plant-Hub#6]
**Humidity Sensor**

- [x] Check if it turns on when I apply power
- [x] Install library and test installation
- [x] Connect to GPIO on Pi
- [x] Fill in humidity function and test in different areas
- [x] Fill in temperature function and test in different areas

**Comment by ffund** [comment]
### Check if it turns on when I apply power

Connect to power as described at [Adafruit](https://learn.adafruit.com/dht/connecting-to-a-dhtxx-sensor).

* VCC - left-most pin connects to 3.3V
* Ground - right-most pin

![image](https://user-images.githubusercontent.com/2316553/112021472-b608e400-8b07-11eb-9649-4723b075957c.png)


Expected result: none, but at least make sure it doesn't get hot or anything.
What to show: show photograph of sensor and connection to Pi.

**Comment by ffund** [comment]
### Connect to GPIO on Pi

* Connect the data wire with 10k pull-up, as shown.

**Comment by ffund** [comment]
### Install library and test installation

Following the instructions at [Github](https://github.com/adafruit/Adafruit_CircuitPython_DHT): 

```
sudo pip3 install adafruit-circuitpython-dht
```

To test if installation worked: open a `python3` terminal, and run:

```
import adafruit_dht
```

Expected result: installs with no fatal errors, and we are able to import the library afterwards.
What to show: if successful, show the Python terminal output. If unsuccessful, show the output when you try to install; also show the error when you try to import.

**Comment by ffund** [comment]
### Connect to GPIO on Pi

Connect the data wire with 10k pull-up, as shown.

Follow the [usage example](https://github.com/adafruit/Adafruit_CircuitPython_DHT#usage-example) for the library. In `python3` terminal, make sure you can get a reading:

```
import adafruit_dht
from board import <pin>
dht_device = adafruit_dht.DHT11(<pin>)
temperature = dht_device.temperature
humidity = dht_device.humidity
```

Note:

> These properties may raise an exception if a problem occurs. You should use try/raise logic and catch RuntimeError and then retry getting the values after at least 2 seconds. If you try again to get a result within 2 seconds, cached values are returned.

Expected result: gets value, no error.
What to show: the Python code you ran and its output. Also photograph of sensor connected to Pi.

**Comment by keidyalmonte** [comment]
> ### Check if it turns on when I apply power
> Connect to power as described at [Adafruit](https://learn.adafruit.com/dht/connecting-to-a-dhtxx-sensor).
> 
> * VCC - left-most pin connects to 3.3V
> * Ground - right-most pin
> 
> ![image](https://user-images.githubusercontent.com/2316553/112021472-b608e400-8b07-11eb-9649-4723b075957c.png)
> 
> Expected result: none, but at least make sure it doesn't get hot or anything.
> What to show: show photograph of sensor and connection to Pi.

**Photograph of sensor and connection to Pi**
![image](https://user-images.githubusercontent.com/60752427/113516698-b2cf1880-9549-11eb-8933-0063459fa76a.png)

**Comment by keidyalmonte** [comment]
> ### Install library and test installation
> Following the instructions at [Github](https://github.com/adafruit/Adafruit_CircuitPython_DHT):
> 
> ```
> sudo pip3 install adafruit-circuitpython-dht
> ```
> 
> To test if installation worked: open a `python3` terminal, and run:
> 
> ```
> import adafruit_dht
> ```
> 
> Expected result: installs with no fatal errors, and we are able to import the library afterwards.
> What to show: if successful, show the Python terminal output. If unsuccessful, show the output when you try to install; also show the error when you try to import.

**Successful Installation of Libraries**

![image](https://user-images.githubusercontent.com/60752427/113177630-bd24a600-921b-11eb-8a2a-0ed9c5428fe7.png)

**Was able to successfully import the Adafruit DHT library**
![image](https://user-images.githubusercontent.com/60752427/113177851-f6f5ac80-921b-11eb-9f9b-7d71ed455fea.png)

**Comment by keidyalmonte** [comment]
> ### Connect to GPIO on Pi
> Connect the data wire with 10k pull-up, as shown.
> 
> Follow the [usage example](https://github.com/adafruit/Adafruit_CircuitPython_DHT#usage-example) for the library. In `python3` terminal, make sure you can get a reading:
> 
> ```
> import adafruit_dht
> from board import <pin>
> dht_device = adafruit_dht.DHT11(<pin>)
> temperature = dht_device.temperature
> humidity = dht_device.humidity
> ```
> 
> Note:
> 
> > These properties may raise an exception if a problem occurs. You should use try/raise logic and catch RuntimeError and then retry getting the values after at least 2 seconds. If you try again to get a result within 2 seconds, cached values are returned.
> 
> Expected result: gets value, no error.
> What to show: the Python code you ran and its output. Also photograph of sensor connected to Pi.

**Expected Result was achieved, however, after a few buffer errors, which were fixed once I tried the code again**
![image](https://user-images.githubusercontent.com/60752427/113187593-08908180-9227-11eb-8c8b-0daa3646866c.png)

**Comment by keidyalmonte** [comment]
### Fill in humidity function and test in different areas
### Fill in temperature function and test in different areas
For these specific functions, it was originally planned to separate them in order to test the specific functionalities of the sensor, however, the libraries provided by the DHT11 sensor required both readings to be done at the same time. For simplicity, the two test functions were combined together.

[Circuit Basics](https://www.circuitbasics.com/how-to-set-up-the-dht11-humidity-sensor-on-the-raspberry-pi/) is referenced for code

![image](https://user-images.githubusercontent.com/60752427/113588094-b623dc00-95fd-11eb-86d0-66f68c774cd9.png)



**Expected Results: Successful testing**
I used the following code to test the sensor using the demo function.
`sudo python demo.py install`
Which allowed me to view the temperature and humidity readings across several places in my vicinity.
![image](https://user-images.githubusercontent.com/60752427/113513663-d89ff180-9538-11eb-928e-afdf494e68d7.png)
